In [7]:
#table logika AND 2 input
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
"""
X1     X2     y
1      1      1
1      0      0
0      0      0
0      0      0
"""

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


'\nX1     X2     y\n1      1      1\n1      0      0\n0      0      0\n0      0      0\n'

In [8]:
#machine learning
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")

import keras
import numpy as np

#model
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model.compile(optimizer='sgd', loss='mean_squared_error')

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
#set data
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
xs = np.array([[1, 1], [1, 0], [0, 1],[0, 0]],dtype=int)
ys = np.array([1, 0, 0, 0],dtype=int)

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


In [10]:
#Menampilkan arsitektur awal
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
model.summary()

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
#cek bobot model awal
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
weights = model.get_weights()
weights

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


[array([[-0.78089947],
        [ 0.13526237]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
#training
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
model.fit(xs, ys, epochs=1000)

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032
Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 457ms/step - loss: 0.8341
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 245ms/step - loss: 0.8010
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7699
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.7407
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.7131
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.6872
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.6628
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.6398
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.6182
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.5977
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.5785
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5604
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.5432
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.5271
Epoch 15/

In [13]:
#test
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
data = [1,1]
answer = model.predict(np.array([data]))
print(answer)

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.72998965]]


In [14]:
weights = model.get_weights()
weights

[array([[0.47236505],
        [0.47846088]], dtype=float32),
 array([-0.2208363], dtype=float32)]

In [15]:
#table data

"""
w1 = 2
w2 = 4

x1     x2     y
2      3      16
4      1      12
5      4      28
7      5      34
8      2      24
2      1      8
4      9      44
8      2      24
7      1      18
6      5      32
1      1      6
3      2      14
"""

'\nw1 = 2\nw2 = 4\n\nx1     x2     y\n2      3      16\n4      1      12\n5      4      28\n7      5      34\n8      2      24\n2      1      8\n4      9      44\n8      2      24\n7      1      18\n6      5      32\n1      1      6\n3      2      14\n'

In [29]:
#model
model2 = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

#set data
xs = np.array([[2, 3], [4, 1], [5, 4], [7, 5],[8, 2],[2, 1],[4, 9],[8, 2],[7, 1],[6, 5],[1, 1],[3, 2]],dtype=int)
ys = np.array([16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14],dtype=int)

In [30]:
#cek bobot model awal
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
weights = model2.get_weights()
weights

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032


[array([[ 0.7433144 ],
        [-0.76705474]], dtype=float32),
 array([0.], dtype=float32)]

In [32]:
#training
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
model2.fit(xs, ys, epochs=1000)

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032
Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step - loss: 557.5793
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 71.3619
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 37.9828
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 30.0371
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 24.5672
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 20.1484
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 16.5376
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 13.5849
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 11.1700
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 9.1952
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.5801
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 6.2592
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 5.1790
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 4.2955


In [33]:
#test
print("Nama: Selfandy Fajar Kautsara Rahutama \nNPM: 41155050210032")
data = [3,3]
answer = model2.predict(np.array([data]))
print(answer)

#seharusnya 3*2 + 3*4 = 18

Nama: Selfandy Fajar Kautsara Rahutama 
NPM: 41155050210032
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[18.167439]]


In [34]:
weights = model2.get_weights()
weights

[array([[2.0013041],
        [4.029325 ]], dtype=float32),
 array([0.07555215], dtype=float32)]